[package]
name = "rusti"
version = "0.1.0"
authors = ["Jack Frost <j4qfrost@gmail.com>"]
edition = "2018"

[features]
cache  = []

[dependencies]
serenity = "0.6.0"
# lapin-async = "0.22.0"
reqwest = "0.9.19"
serde = "1.0.97"
serde_json = "1.0.40"