version: "3"
services:
  rusti-bot:
    image: rusti-bot
    container_name: rusti-bot
    environment:
      RUST_BACKTRACE: full
      BROKER_HOST: broker
      BROKER_PORT: 5672
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      TRAVIS_TOKEN: ${TRAVIS_TOKEN}
#   redispeech-rust:
#     image: redispeech-rust
#     # build: .
#     container_name: redispeech
#     environment:
#       RUST_BACKTRACE: 1
#       BROKER_HOST: broker
#       BROKER_PORT: 5672
#     volumes:
#       - type: bind
#         source: ../models
#         target: /models
# networks:
#  default:
#   name: broker