version: "3"
services:
  rusti-bot:
    build: .
    container_name: rusti-bot
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redispeech:
    build: ./redispeech
    container_name: redispeech
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
networks:
 default:
  name: redis