version: "3.7"
services:
  rusti-bot:
    image: rusti-bot
    container_name: rusti-bot
    environment:
      RUST_BACKTRACE: full
      BROKER_HOST: broker
      BROKER_PORT: 5672
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      TRAVIS_TOKEN: ${TRAVIS_TOKEN}
      WEBHOOK_HOST: rusti-bot
      WEBHOOK_PORT: 8080
      RUST_LOG: rusti=debug,webhook=debug
    expose:
      - "8080"
#   redispeech-rust:
#     image: redispeech-rust
#     # build: .
#     container_name: redispeech
#     environment:
#       RUST_BACKTRACE: 1
#       BROKER_HOST: broker
#       BROKER_PORT: 5672
#     volumes:
#       - type: bind
#         source: ../models
#         target: /models

  serveo:
    image: taichunmin/serveo:latest
    tty: true
    stdin_open: true
    # see https://serveo.net/ for more options
    command: autossh -M 0 -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -o StrictHostKeyChecking=no -R rusti:80:rusti-bot:8080 serveo.net
  

networks:
 default:
  name: rusti